<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/helloword.proto

namespace Helloword;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>helloword.MsgReq</code>
 */
class MsgReq extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pb\Helloword::initOnce();
        parent::__construct($data);
    }

}

