<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/helloword.proto

namespace GPBMetadata\Pb;

class Helloword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f020a1270622f68656c6c6f776f72642e70726f746f120968656c6c6f" .
            "776f726422290a0c48656c6c6f52657175657374120c0a046e616d651801" .
            "20012809120b0a03616765180220012805221d0a0a48656c6c6f5265706c" .
            "79120f0a076d65737361676518012001280922080a064d73675265712215" .
            "0a064d7367526570120b0a036d736718012001280932760a074772656574" .
            "6572123c0a0853617948656c6c6f12172e68656c6c6f776f72642e48656c" .
            "6c6f526571756573741a152e68656c6c6f776f72642e48656c6c6f526570" .
            "6c792200122d0a034d736712112e68656c6c6f776f72642e4d7367526571" .
            "1a112e68656c6c6f776f72642e4d736752657022004213420f48656c6c6f" .
            "576f726c6450726f746f5001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

